# Generated by Django 5.2.13 on 2026-05-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('ORGANIZER', 'Organizer'), ('AGENT', 'Agent'), ('ADMIN', 'Admin')], default='CLIENT', max_length=10),
        ),
    ]
