# Generated by Django 5.2.13 on 2026-05-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('ORGANIZER', 'Organizer'), ('AGENT', 'Agent'), ('CONTROLLER', 'Controller'), ('ADMIN', 'Admin')], default='CLIENT', max_length=12),
        ),
    ]
