# Generated by Django 5.2.13 on 2026-05-08 01:27

from django.db import migrations, models


def convert_organizer_users(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='ORGANIZER').update(role='CLIENT')


def delete_organizer_requests(apps, schema_editor):
    OrganizerRequest = apps.get_model('accounts', 'OrganizerRequest')
    OrganizerRequest.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role_organizerrequest'),
    ]

    operations = [
        migrations.RunPython(delete_organizer_requests),
        migrations.RunPython(convert_organizer_users),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('AGENT', 'Agent'), ('ADMIN', 'Admin')], default='CLIENT', max_length=12),
        ),
        migrations.DeleteModel(
            name='OrganizerRequest',
        ),
    ]
