# Generated by Django 5.2.13 on 2026-05-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('CONCERT', 'Concert'), ('FESTIVAL', 'Festival'), ('SPORT', 'Sport'), ('THEATRE', 'Theatre'), ('COMEDY', 'Comedy'), ('CONFERENCE', 'Conference'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
