# Generated by Django 5.2.13 on 2026-05-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='qr_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='qr_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='qr_signature',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
