# Generated by Django 5.2.13 on 2026-05-04 23:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_qr_generated_at_ticket_qr_payload_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure')], max_length=10)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_logs', to='tickets.ticket')),
                ('validated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-validated_at'],
            },
        ),
    ]
