# Generated by Django 5.2.13 on 2026-05-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_validationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationlog',
            name='sync_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('CONFLICT', 'Conflict')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='validationlog',
            name='ticket_id_raw',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='validationlog',
            name='validation_mode',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='ONLINE', max_length=10),
        ),
    ]
