# Generated by Django 5.2.13 on 2026-05-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_validationlog_sync_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='stripe_session_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
